var GLOBAL = {
    METHOD: {
        TABS: "tabs",
        TABS_HIS: "tabs-his",
        GOTO_TAB: "goto_tab",
        CACHE_LOAD: "cache_load",
    },
    KEY: {
        ESC: "ESC",
        DUPLICATE_TAB: "DUPLICATE_TAB",
        SEARCH_PANEL: "SEARCH_PANEL",
        SWITCH_PANEL_UP: "SWITCH_PANEL_UP",
        SWITCH_PANEL_DOWN: "SWITCH_PANEL_DOWN",
        SWITCH_PANEL_GOTO: "SWITCH_PANEL_GOTO",
    },
    KEY_BIND_CACHE: "keyBinds",
    FUNC: {
        COPY: "COPY",
        SWITCH_PREV: "SWITCH_PREV",
        SWITCH_NEXT: "SWITCH_NEXT",
        SEARCH: "SEARCH",
    },
    IMG: {
        TAB_ICON_WHITE: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMwAAADABAMAAAC6zpG6AAAAFVBMVEVHcEzV1dX////V1dX8/Pz////V1dXOoMA3AAAAB3RSTlMAq7DZ4//+D6G54gAAAOlJREFUeNrt2zEKgzAUgOFXMJ2bnqCIFxDBuYMHcPB1FqS9/xFKXJ+0RIwp9f/HQPiSkPUJERER/X7XMlRV3dyg0Q1DN1eVoZssVejm3cWmCRKT0wT1u1xGdZfL2Os8NUkP82Z7vJozS/YUo0Rm/7QzK/YYvURWmE1OVcevO2JbZORTMDAwMDAwMNHMmmBgcjKbBwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA3NwJkV/zogmKs9Y6VmTNGaaLJaTD9VNqG3b16qmaWpCde299xcm6YmIiFb3BnVgoLnoscsFAAAAAElFTkSuQmCC",
        TAB_ICON_BLACK: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMwAAADACAMAAAB/Pny7AAAAOVBMVEVHcEz09PT29vb09PTs7OyKioohISEAAAAqKioAAADR0dEqKioAAAC2traFhYVhYWErKysWFhYAAAAcCerwAAAADXRSTlMAFi9Qc42gtcbR1ebpDKzJVAAAAZBJREFUeNrt3ctygjAAhtEQLiq1Crz/w9Y23jYVsQNj6PnWmYEzP6wTJEmSJEnSlGJVN02zaTap3bn9tWH29sP+2i612W1Szam6iuGp2n7IoL4N48XjkEnHODpLsuShaccta9HEw5BVh5j9v3+rb0eGWc00d19j9V2Zij8Vp9Kx4lRMlanq1O1/68JfKkJ60oOO12nCr9WXI4/Azwwb5u7Qjz/psksVXqrql8KEbkjVo5jwKuawFOb2qvNhwlKYEmZSJcwrxQmYEibExTDFmjABZlIFzJtiAszcmAgDAwMzuWHpJnDfGGOZ/DGFZSwzP+b9O864zPKtaZlgGctYxjLPnICBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgVkdJp9g3rzqn1xB2XZ5Wbo2POizz8nSf4ZU9tukXcav005tm+2lj7u65fq4a3uu2TapuoouP5ckSZIkzdsXWGGIGb9nUtQAAAAASUVORK5CYII=",
    }
}